# Which Campaigns are Actually Worth the Spend?

### 1. Load the dataset.
Then check the basics:
- dimensionality (rows, columns)
- column names, datatypes, and number of non-null values
- descriptive statistics (for numerical columns)
- are there any missing values?

In [10]:
import pandas as pd
url = "https://raw.githubusercontent.com/super-unknowledge/campaign-analysis-1/refs/heads/main/synthetic_social_media_campaign_data.csv"
df = pd.read_csv(url)

df.head()

,campaign_id,campaign_name,platform,post_type,post_date,post_time,content_theme,target_audience,boosted_post,spend_usd,...,conversions,conversion_value_usd,cpc_usd,ctr,engagement_rate,hashtag_count,emoji_count,word_count,sentiment_score,video_length_seconds
0,CMP1000,Summer Campaign 2025,TikTok,Story,1/8/2024,13:45,Promotion,"Gen Z (18-24, Urban)",False,8.46,...,25,503.43,0.05,0.0297,0.0883,9,2,18,0.12,37
1,CMP1000,Back to School Campaign 2024,X,Video,1/3/2024,19:30,Behind-the-Scenes,"Parents (30-45, Suburban)",True,7.07,...,5,249.50,0.14,0.0098,0.0320,2,0,12,-0.16,22
2,CMP1000,Spring Campaign 2025,LinkedIn,Story,1/20/2024,9:30,User Testimonial,"Gen Z (18-24, Urban)",True,40.60,...,56,2138.28,0.11,0.0300,0.1152,13,5,16,0.30,113
3,CMP1000,Summer Campaign 2024,Facebook,Image,1/14/2024,11:00,User Testimonial,"Gen X (35-50, Mixed)",True,5.23,...,19,1360.52,0.03,0.0553,0.1167,1,9,45,-0.39,0
4,CMP1000,Spring Campaign 2025,Instagram,Video,1/4/2024,11:00,Behind-the-Scenes,"Millennials (25-34, Suburban)",False,5.38,...,10,1312.49,0.07,0.0244,0.0694,13,2,40,-0.11,119

In [11]:
df.shape

(1610, 24)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1610 entries, 0 to 1609
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   campaign_id           1610 non-null   object
 1   campaign_name         1610 non-null   object
 2   platform              1610 non-null   object
 3   post_type             1610 non-null   object
 4   post_date             1610 non-null   object
 5   post_time             1610 non-null   object
 6   content_theme         1610 non-null   object
 7   target_audience       1610 non-null   object
 8   boosted_post          1610 non-null   bool
 9   spend_usd             1610 non-null   float64
 10  reach                 1610 non-null   int64
 11  impressions           1610 non-null   int64
 12  engagements           1610 non-null   int64
 13  clicks                1610 non-null   int64
 14  conversions           1610 non-null   int64
 15  conversion_value_usd  1610 non-null   float64
 16  cpc_usd               1610 non-null   float64
 17  ctr                   1610 non-null   float64
 18  engagement_rate       1610 non-null   float64
 19  hashtag_count         1610 non-null   int64
 20  emoji_count           1610 non-null   int64
 21  word_count            1610 non-null   int64
 22  sentiment_score       1610 non-null   float64
 23  video_length_seconds  1610 non-null   int64
dtypes: bool(1), float64(6), int64(9), object(8)
memory usage: 291.0+ KB

In [13]:
df.describe()

,spend_usd,reach,impressions,engagements,clicks,conversions,conversion_value_usd,cpc_usd,ctr,engagement_rate,hashtag_count,emoji_count,word_count,sentiment_score,video_length_seconds
count,1610.000000,1610.000000,1610.000000,1610.000000,1610.000000,1610.000000,1610.000000,1610.000000,1610.000000,1610.000000,1610.000000,1610.000000,1610.000000,1610.000000,1610.000000
mean,37.921410,5677.191925,7577.076398,397.242857,198.421118,24.656522,1947.463789,0.242106,0.025947,0.069577,7.454037,5.114907,27.573292,0.183379,38.767702
std,49.690521,3542.976873,4596.120964,315.775973,167.967635,24.441697,2435.286218,0.327396,0.013041,0.028743,4.549370,3.174023,13.118617,0.464015,40.813124
min,0.010000,166.000000,259.000000,4.000000,1.000000,0.000000,0.000000,0.000000,0.003400,0.019100,0.000000,0.000000,5.000000,-1.000000,0.000000
25%,4.962500,3226.250000,4328.750000,171.000000,80.000000,9.000000,471.580000,0.040000,0.015600,0.044600,3.000000,2.000000,16.000000,-0.140000,0.000000
50%,17.355000,5247.000000,7106.000000,326.000000,156.000000,18.000000,1123.225000,0.140000,0.024000,0.068700,7.500000,5.000000,27.000000,0.190000,24.000000
75%,52.972500,7428.750000,9823.750000,542.000000,267.750000,33.000000,2494.772500,0.320000,0.034275,0.094100,11.000000,8.000000,39.000000,0.510000,75.000000
max,425.390000,28457.000000,33893.000000,2684.000000,1337.000000,220.000000,21624.050000,3.650000,0.069900,0.119900,15.000000,10.000000,50.000000,1.000000,120.000000

In [14]:
print(df.isnull().sum())

campaign_id             0
campaign_name           0
platform                0
post_type               0
post_date               0
post_time               0
content_theme           0
target_audience         0
boosted_post            0
spend_usd               0
reach                   0
impressions             0
engagements             0
clicks                  0
conversions             0
conversion_value_usd    0
cpc_usd                 0
ctr                     0
engagement_rate         0
hashtag_count           0
emoji_count             0
word_count              0
sentiment_score         0
video_length_seconds    0
dtype: int64

Let's peek at the unique values of some of the columns we'll use later:

In [ ]:
# Check unique values for platform column
# 1. Get the number of unique platforms
unique_count = df['platform'].nunique()

# 2. Get the list of all unique platforms
unique_values = df['platform'].unique()

print(unique_count, unique_values)

5 ['TikTok' 'X' 'LinkedIn' 'Facebook' 'Instagram']

In [ ]:
# Check unique values for post_type column
# 1. Get the number of unique post types
unique_count = df['post_type'].nunique()

# 2. Get the list of all unique post types
unique_values = df['post_type'].unique()

print(unique_count, unique_values)

5 ['Story' 'Video' 'Image' 'Carousel' 'Reel']

In [ ]:
# Check unique values for content_theme column
# 1. Get the number of unique content themes
unique_count = df['content_theme'].nunique()

# 2. Get the list of all unique content themes
unique_values = df['content_theme'].unique()

print(unique_count, unique_values)

5 ['Promotion' 'Behind-the-Scenes' 'User Testimonial' 'Product Launch'
 'Lifestyle']

Takeaways: 
- The dataset has 1,610 rows and 24 columns
- `post_date` and `post_time` are listed as "object". They'll need to be converted into datetime later. But since we're focusing on figuring out which campaigns are worth the spend, we'll leave them as is for now since they're we don't need that information.
- There are no missing values, and nothing to really clean since this is a generated dataset (Hooray!)

### 2. Perform the initial exploration.
We want to find out the following metrics:
- ROAS (Return on Ad Spend) = Conversion Value / Spend
- Cost per Conversion = Spend / Conversions
- Conversion Rate = Conversions / Clicks
- Efficiency Score = rank campaigns by ROAS within each platform

In Part 2 when we create the pipeline, we'll use postgres as our DB. SQL query versions of each line are left as comments where applicable.

In [19]:
# Only look at rows where we spend money and have conversions
# WHERE spend_usd > 0 AND conversions > 0
clean = df[(df['spend_usd'] > 0) & (df['conversions'] > 0)].copy()

# ROAS = Conversion Value / Spend
# Derived metric: Revenue per dollar spent
clean['roas'] = clean['conversion_value_usd'] / clean['spend_usd']

# Cost per Conversion = Spend / Conversions
# We know from the blog post that cpc_usd is cost per click, not conversion
# Derived metric: How much did we pay for each conversion?
clean['cost_per_conversion'] = clean['spend_usd'] / clean['conversions']

# Conversion Rate = Conversions / Clicks
# Derived metric: What percentage of the people who clicked get converted?
clean['conversion_rate'] = clean['conversions'] / clean['clicks']

# Efficiency Score
# Derived metric: Which campaigns have the best return per platform?
# Rank by ROAS within each Platform (Highest ROAS gets Rank 1)
clean['efficiency_rank'] = clean.groupby('platform')['roas'].rank(ascending=False, method='min')

In [20]:
# Assuming we sorted the final DataFrame for clear reading:
df_sorted = clean.sort_values(by=['platform', 'efficiency_rank'])
print(df_sorted[['platform', 'campaign_name', 'roas', 'efficiency_rank']].to_string(index=False))

 platform                campaign_name          roas  efficiency_rank
 Facebook        Holiday Campaign 2024  28878.090909              1.0
 Facebook        Holiday Campaign 2025  11071.428571              2.0
 Facebook           Fall Campaign 2024  10996.256410              3.0
 Facebook Back to School Campaign 2025  10393.140845              4.0
 Facebook Back to School Campaign 2024   6438.107143              5.0
 Facebook         Spring Campaign 2025   5870.884615              6.0
 Facebook        Holiday Campaign 2024   4370.374046              7.0
 Facebook         Summer Campaign 2024   4309.238095              8.0
 Facebook         Spring Campaign 2025   3253.820690              9.0
 Facebook         Summer Campaign 2024   2590.857143             10.0
 Facebook         Summer Campaign 2024   2218.392857             11.0
 Facebook         Spring Campaign 2024   2174.661224             12.0
 Facebook         Spring Campaign 2024   1897.000000             13.0
 Facebook        Holiday Campaign 2025   1782.548387             14.0
 Facebook Back to School Campaign 2024   1721.716129             15.0
 Facebook Back to School Campaign 2025   1678.955224             16.0
 Facebook Back to School Campaign 2024   1631.656934             17.0
 Facebook         Spring Campaign 2024   1511.809689             18.0
 Facebook           Fall Campaign 2025   1509.107955             19.0
 Facebook        Holiday Campaign 2025   1420.500000             20.0
 Facebook Back to School Campaign 2024   1378.571429             21.0
 Facebook         Summer Campaign 2025   1375.107438             22.0
 Facebook        Holiday Campaign 2024   1338.592593             23.0
 Facebook           Fall Campaign 2024   1274.026786             24.0
 Facebook Back to School Campaign 2024   1269.054264             25.0
 Facebook           Fall Campaign 2024   1158.511111             26.0
 Facebook           Fall Campaign 2025   1093.035714             27.0
 Facebook         Summer Campaign 2025    992.847769             28.0
 Facebook        Holiday Campaign 2025    943.854111             29.0
 Facebook         Spring Campaign 2025    930.367347             30.0
 Facebook Back to School Campaign 2025    803.236324             31.0
 Facebook         Spring Campaign 2025    740.427660             32.0
 Facebook           Fall Campaign 2024    732.936842             33.0
 Facebook Back to School Campaign 2025    715.690789             34.0
 Facebook         Spring Campaign 2025    704.606557             35.0
 Facebook           Fall Campaign 2025    679.294118             36.0
 Facebook         Spring Campaign 2025    651.267327             37.0
 Facebook Back to School Campaign 2024    622.614286             38.0
 Facebook           Fall Campaign 2025    611.111111             39.0
 Facebook         Summer Campaign 2024    602.830357             40.0
 Facebook         Spring Campaign 2025    589.137931             41.0
 Facebook        Holiday Campaign 2025    579.305389             42.0
 Facebook         Spring Campaign 2025    540.230620             43.0
 Facebook         Spring Campaign 2025    478.893023             44.0
 Facebook           Fall Campaign 2025    477.341463             45.0
 Facebook         Spring Campaign 2024    476.704225             46.0
 Facebook         Spring Campaign 2024    466.774453             47.0
 Facebook        Holiday Campaign 2024    403.934211             48.0
 Facebook           Fall Campaign 2024    401.232000             49.0
 Facebook        Holiday Campaign 2025    400.539474             50.0
 Facebook         Spring Campaign 2025    390.498759             51.0
 Facebook Back to School Campaign 2025    390.463694             52.0
 Facebook         Summer Campaign 2025    389.865517             53.0
 Facebook         Summer Campaign 2025    382.645669             54.0
 Facebook Back to School Campaign 2024    363.175439             55.0
 Facebook           Fall Campaign 2024    326.539493             56.0
 Facebook        Holiday Campaign 2024    321.066494             57.0
 Facebook Back to School Campaign 2025    319.567742             58.0
 Facebook Back to School Campaign 2025    296.557070             59.0
 Facebook           Fall Campaign 2025    293.997472             60.0
 Facebook           Fall Campaign 2024    283.645833             61.0
 Facebook        Holiday Campaign 2025    282.089319             62.0
 Facebook         Spring Campaign 2025    281.888438             63.0
 Facebook           Fall Campaign 2025    275.761671             64.0
 Facebook         Summer Campaign 2024    271.868056             65.0
 Facebook         Spring Campaign 2025    270.692790             66.0
 Facebook         Spring Campaign 2024    261.451948             67.0
 Facebook         Summer Campaign 2024    260.137667             68.0
 Facebook           Fall Campaign 2025    251.365093             69.0
 Facebook        Holiday Campaign 2024    245.217877             70.0
 Facebook Back to School Campaign 2024    244.123217             71.0
 Facebook         Spring Campaign 2024    236.857143             72.0
 Facebook         Summer Campaign 2024    234.357353             73.0
 Facebook Back to School Campaign 2025    221.374124             74.0
 Facebook Back to School Campaign 2024    221.126253             75.0
 Facebook        Holiday Campaign 2025    221.060674             76.0
 Facebook           Fall Campaign 2025    220.611241             77.0
 Facebook           Fall Campaign 2024    214.133333             78.0
 Facebook         Spring Campaign 2025    204.054688             79.0
 Facebook        Holiday Campaign 2025    204.003771             80.0
 Facebook        Holiday Campaign 2025    203.527086             81.0
 Facebook        Holiday Campaign 2025    200.220339             82.0
 Facebook        Holiday Campaign 2024    195.718750             83.0
 Facebook         Spring Campaign 2024    195.558505             84.0
 Facebook         Spring Campaign 2025    191.722981             85.0
 Facebook         Spring Campaign 2024    184.564885             86.0
 Facebook         Summer Campaign 2024    177.450098             87.0
 Facebook           Fall Campaign 2025    175.456019             88.0
 Facebook Back to School Campaign 2024    174.719705             89.0
 Facebook Back to School Campaign 2024    169.068100             90.0
 Facebook         Spring Campaign 2025    166.646333             91.0
 Facebook Back to School Campaign 2024    166.598639             92.0
 Facebook         Summer Campaign 2024    163.384236             93.0
 Facebook Back to School Campaign 2025    161.328416             94.0
 Facebook         Spring Campaign 2025    153.639340             95.0
 Facebook Back to School Campaign 2025    152.488253             96.0
 Facebook           Fall Campaign 2025    151.323864             97.0
 Facebook           Fall Campaign 2024    151.102532             98.0
 Facebook         Spring Campaign 2024    150.451777             99.0
 Facebook         Summer Campaign 2025    148.414261            100.0
 Facebook         Summer Campaign 2025    147.043299            101.0
 Facebook           Fall Campaign 2025    145.124088            102.0
 Facebook           Fall Campaign 2025    142.441230            103.0
 Facebook         Summer Campaign 2025    142.274921            104.0
 Facebook           Fall Campaign 2025    141.931138            105.0
 Facebook         Summer Campaign 2025    141.836180            106.0
 Facebook           Fall Campaign 2024    138.116494            107.0
 Facebook         Summer Campaign 2025    135.291790            108.0
 Facebook           Fall Campaign 2025    131.707941            109.0
 Facebook           Fall Campaign 2025    131.619677            110.0
 Facebook         Spring Campaign 2024    130.725396            111.0
 Facebook         Summer Campaign 2025    128.580786            112.0
 Facebook           Fall Campaign 2025    117.345085            113.0
 Facebook Back to School Campaign 2025    116.665757            114.0
 Facebook        Holiday Campaign 2024    113.616205            115.0
 Facebook        Holiday Campaign 2025    109.040044            116.0
 Facebook         Spring Campaign 2024    108.632332            117.0
 Facebook           Fall Campaign 2025    106.929389            118.0
 Facebook           Fall Campaign 2025    102.578002            119.0
 Facebook         Summer Campaign 2024    102.344498            120.0
 Facebook         Summer Campaign 2025    101.777054            121.0
 Facebook         Spring Campaign 2024    101.033917            122.0
 Facebook        Holiday Campaign 2025     99.144425            123.0
 Facebook Back to School Campaign 2025     97.963753            124.0
 Facebook         Spring Campaign 2025     96.488889            125.0
 Facebook         Summer Campaign 2024     96.272351            126.0
 Facebook           Fall Campaign 2024     93.606583            127.0
 Facebook         Spring Campaign 2024     91.753247            128.0
 Facebook         Summer Campaign 2024     91.735284            129.0
 Facebook Back to School Campaign 2024     89.916312            130.0
 Facebook           Fall Campaign 2024     89.596083            131.0
 Facebook        Holiday Campaign 2024     85.135103            132.0
 Facebook         Spring Campaign 2024     83.421458            133.0
 Facebook Back to School Campaign 2024     83.098971            134.0
 Facebook           Fall Campaign 2024     82.490446            135.0
 Facebook           Fall Campaign 2025     81.512972            136.0
 Facebook        Holiday Campaign 2024     81.257987            137.0
 Facebook Back to School Campaign 2024     80.503051            138.0
 Facebook        Holiday Campaign 2025     79.428571            139.0
 Facebook           Fall Campaign 2024     79.317857            140.0
 Facebook Back to School Campaign 2024     78.552001            141.0
 Facebook         Spring Campaign 2024     77.753757            142.0
 Facebook Back to School Campaign 2024     77.236080            143.0
 Facebook        Holiday Campaign 2024     76.366270            144.0
 Facebook           Fall Campaign 2024     75.565346            145.0
 Facebook Back to School Campaign 2025     75.277596            146.0
 Facebook         Summer Campaign 2025     74.306122            147.0
 Facebook Back to School Campaign 2025     73.638762            148.0
 Facebook           Fall Campaign 2024     72.227690            149.0
 Facebook           Fall Campaign 2025     70.563525            150.0
 Facebook         Summer Campaign 2024     69.550699            151.0
 Facebook         Summer Campaign 2025     69.459601            152.0
 Facebook           Fall Campaign 2024     68.960074            153.0
 Facebook         Summer Campaign 2025     66.826512            154.0
 Facebook         Summer Campaign 2025     66.517477            155.0
 Facebook Back to School Campaign 2024     66.037674            156.0
 Facebook         Summer Campaign 2025     65.117832            157.0
 Facebook         Summer Campaign 2024     62.635747            158.0
 Facebook           Fall Campaign 2024     62.606952            159.0
 Facebook        Holiday Campaign 2024     60.690821            160.0
 Facebook           Fall Campaign 2024     60.632314            161.0
 Facebook Back to School Campaign 2025     58.934155            162.0
 Facebook         Spring Campaign 2025     57.944683            163.0
 Facebook Back to School Campaign 2025     57.390181            164.0
 Facebook        Holiday Campaign 2024     56.230205            165.0
 Facebook         Summer Campaign 2024     55.990295            166.0
 Facebook         Spring Campaign 2025     54.654558            167.0
 Facebook         Spring Campaign 2024     53.803010            168.0
 Facebook         Summer Campaign 2024     52.295711            169.0
 Facebook Back to School Campaign 2024     51.941593            170.0
 Facebook         Summer Campaign 2025     51.736973            171.0
 Facebook Back to School Campaign 2024     50.691953            172.0
 Facebook        Holiday Campaign 2024     50.327095            173.0
 Facebook           Fall Campaign 2024     49.902516            174.0
 Facebook Back to School Campaign 2025     49.797645            175.0
 Facebook         Spring Campaign 2025     49.163349            176.0
 Facebook        Holiday Campaign 2025     48.638783            177.0
 Facebook Back to School Campaign 2025     47.900702            178.0
 Facebook         Spring Campaign 2025     47.373315            179.0
 Facebook           Fall Campaign 2024     46.439072            180.0
 Facebook        Holiday Campaign 2024     46.378354            181.0
 Facebook           Fall Campaign 2025     46.191489            182.0
 Facebook         Summer Campaign 2025     45.311553            183.0
 Facebook        Holiday Campaign 2024     44.098592            184.0
 Facebook         Spring Campaign 2025     43.391167            185.0
 Facebook        Holiday Campaign 2025     40.715862            186.0
 Facebook Back to School Campaign 2024     40.617849            187.0
 Facebook           Fall Campaign 2025     38.896148            188.0
 Facebook         Spring Campaign 2024     38.632896            189.0
 Facebook         Spring Campaign 2025     38.439977            190.0
 Facebook        Holiday Campaign 2024     38.273245            191.0
 Facebook           Fall Campaign 2025     35.399435            192.0
 Facebook           Fall Campaign 2024     35.297432            193.0
 Facebook         Summer Campaign 2024     35.035599            194.0
 Facebook        Holiday Campaign 2024     35.022174            195.0
 Facebook         Summer Campaign 2024     34.925905            196.0
 Facebook         Spring Campaign 2025     34.884666            197.0
 Facebook Back to School Campaign 2024     34.531568            198.0
 Facebook           Fall Campaign 2024     33.650401            199.0
 Facebook        Holiday Campaign 2025     33.217756            200.0
 Facebook           Fall Campaign 2025     32.945215            201.0
 Facebook        Holiday Campaign 2025     32.192927            202.0
 Facebook Back to School Campaign 2024     32.110043            203.0
 Facebook         Spring Campaign 2025     32.068183            204.0
 Facebook Back to School Campaign 2024     31.806260            205.0
 Facebook         Summer Campaign 2024     31.580753            206.0
 Facebook        Holiday Campaign 2025     31.076087            207.0
 Facebook         Summer Campaign 2025     30.688414            208.0
 Facebook         Spring Campaign 2025     30.643561            209.0
 Facebook         Spring Campaign 2025     29.667978            210.0
 Facebook Back to School Campaign 2024     28.807784            211.0
 Facebook         Spring Campaign 2024     28.568345            212.0
 Facebook         Summer Campaign 2024     28.554419            213.0
 Facebook         Spring Campaign 2025     28.292490            214.0
 Facebook         Summer Campaign 2025     27.934885            215.0
 Facebook           Fall Campaign 2025     27.924885            216.0
 Facebook         Spring Campaign 2025     27.715505            217.0
 Facebook         Summer Campaign 2024     27.226502            218.0
 Facebook         Summer Campaign 2025     26.970701            219.0
 Facebook        Holiday Campaign 2025     26.768473            220.0
 Facebook        Holiday Campaign 2024     26.574751            221.0
 Facebook Back to School Campaign 2024     26.476821            222.0
 Facebook Back to School Campaign 2024     23.145967            223.0
 Facebook           Fall Campaign 2025     22.997455            224.0
 Facebook           Fall Campaign 2024     22.868726            225.0
 Facebook Back to School Campaign 2024     22.699635            226.0
 Facebook        Holiday Campaign 2024     22.096756            227.0
 Facebook Back to School Campaign 2024     20.441718            228.0
 Facebook           Fall Campaign 2025     19.928611            229.0
 Facebook           Fall Campaign 2025     19.911526            230.0
 Facebook Back to School Campaign 2025     19.867604            231.0
 Facebook           Fall Campaign 2024     18.416203            232.0
 Facebook           Fall Campaign 2025     18.328603            233.0
 Facebook         Summer Campaign 2024     18.207799            234.0
 Facebook         Summer Campaign 2025     17.646907            235.0
 Facebook           Fall Campaign 2024     17.643101            236.0
 Facebook           Fall Campaign 2024     17.341009            237.0
 Facebook Back to School Campaign 2024     16.779751            238.0
 Facebook Back to School Campaign 2024     16.751628            239.0
 Facebook           Fall Campaign 2024     16.712123            240.0
 Facebook Back to School Campaign 2025     16.601691            241.0
 Facebook        Holiday Campaign 2024     16.555135            242.0
 Facebook Back to School Campaign 2025     16.518925            243.0
 Facebook         Summer Campaign 2025     16.469226            244.0
 Facebook         Summer Campaign 2024     16.253611            245.0
 Facebook         Summer Campaign 2024     16.099207            246.0
 Facebook        Holiday Campaign 2025     15.851139            247.0
 Facebook         Summer Campaign 2024     14.496081            248.0
 Facebook         Summer Campaign 2024     14.159758            249.0
 Facebook        Holiday Campaign 2025     13.167039            250.0
 Facebook         Summer Campaign 2025     13.046651            251.0
 Facebook           Fall Campaign 2025     12.776864            252.0
 Facebook Back to School Campaign 2024     12.740429            253.0
 Facebook         Summer Campaign 2025     12.625054            254.0
 Facebook         Spring Campaign 2024     12.070054            255.0
 Facebook Back to School Campaign 2024     11.863699            256.0
 Facebook         Summer Campaign 2024     11.833459            257.0
 Facebook         Spring Campaign 2025     11.680135            258.0
 Facebook         Spring Campaign 2025     11.367678            259.0
 Facebook           Fall Campaign 2025     11.159113            260.0
 Facebook Back to School Campaign 2024     10.188948            261.0
 Facebook         Summer Campaign 2025     10.088623            262.0
 Facebook        Holiday Campaign 2025      9.555282            263.0
 Facebook         Spring Campaign 2024      9.271036            264.0
 Facebook        Holiday Campaign 2024      9.257961            265.0
 Facebook        Holiday Campaign 2025      9.257948            266.0
 Facebook           Fall Campaign 2024      9.141217            267.0
 Facebook           Fall Campaign 2025      9.090509            268.0
 Facebook        Holiday Campaign 2025      8.965282            269.0
 Facebook Back to School Campaign 2025      8.706118            270.0
 Facebook        Holiday Campaign 2024      8.667418            271.0
 Facebook Back to School Campaign 2024      8.605198            272.0
 Facebook        Holiday Campaign 2025      8.481243            273.0
 Facebook           Fall Campaign 2025      8.253910            274.0
 Facebook           Fall Campaign 2024      8.033952            275.0
 Facebook         Summer Campaign 2024      7.995631            276.0
 Facebook        Holiday Campaign 2024      7.397847            277.0
 Facebook           Fall Campaign 2024      7.232192            278.0
 Facebook        Holiday Campaign 2025      6.960056            279.0
 Facebook         Summer Campaign 2024      6.832000            280.0
 Facebook Back to School Campaign 2024      6.563616            281.0
 Facebook         Summer Campaign 2025      6.543805            282.0
 Facebook           Fall Campaign 2025      6.344988            283.0
 Facebook         Summer Campaign 2024      6.337442            284.0

### 3. Perform A/B testing.
The dataset has multiple Post Types (Image, Video, Carousel, Story). 

So let's answer the question: "Do video posts actually convert better than image posts, or does it just look that way?"

We can do an A/B test by running a two-sample t-test on conversion rates between post types:

In [ ]:
from scipy import stats

video = clean[clean['post_type'] == 'Video']['conversion_rate']
image = clean[clean['post_type'] == 'Image']['conversion_rate']

t_stat, p_value = stats.ttest_ind(video, image)
print(video.count())
print(image.count())
print(f"p-value: {p_value:.4f}")
print("Statistically significant!" if p_value < 0.05 else "No significant difference — could be noise")

326
305
p-value: 0.3002
No significant difference — could be noise

We cannot confidently say video outperforms image on this platform. The difference could be random variation with this sample size.

Let's try answering: "Do Instagram posts convert better than posts on X?"

In [34]:
ig = clean[clean['platform'] == 'Instagram']['conversion_rate']
x = clean[clean['platform'] == 'X']['conversion_rate']

t_stat, p_value = stats.ttest_ind(ig, x)
print(ig.count())
print(x.count())
print(f"p-value: {p_value:.4f}")
print("Statistically significant!" if p_value < 0.05 else "No significant difference — could be noise")

321
351
p-value: 0.0246
Statistically significant!

So, we can say that our posts on Instagram convert than our posts on X. That makes sense intuitively.